Configure TCP or UNIX socket
artefactual-labs/ansible-clamav pull request #6
Opened 2018-04-06 14:35 UTC by mamedin

A new variable `CLAMAV_SOCKET_TYPE` has been added. It can take two
values: "tcp" or "file".

On CentOS and Ubuntu 14 it is configured in the `clamd.conf` file.

On Ubuntu 16 this configuration is more complex because the
clamav-daemon package uses three systemd files to configure the socket
type (unix file or tcp socket). This PR uses debconf-set-selections to
configure the socket type, but the clamav-daemon package doesn't read
the debconf system when upgrading or reinstalling, it is used only when
installing from scratch, so a package purge is needed when changing the
socket type.

The SELinux policies `antivirus_can_scan_system` and `clamd_use_jit` will
be activated if SELinux is enabled on CentOS.

On Ubuntu task files, the "Enable services" task has been modified to
restart the clamav-daemon service instead of starting. It is needed to
apply the changes made by the role.

On Ubuntu the default socket type is UNIX file.
On Centos the default socket type is TCP.

It Fixes #5

2018-04-10 09:06 UTC, scollazo requested changes

2018-04-10 09:06 UTC, scollazo commented on README.md
> +- `CLAMAV_MAX_FILE_SIZE`: (default: "2000M")
Those fields should also have an explanation, not only `CLAMAV_SOCKET_TYPE`

2018-04-10 09:06 UTC, scollazo commented on README.md
> +- `CLAMAV_SOCKET_TYPE`: configure clamad to use a tcp or file socket (default: "file")
It reads `clamad`, typo?

2018-04-10 09:06 UTC, scollazo commented on defaults/main.yml
> +# Available Options for CLAMAV_SOCKET_TYPE are "tcp" and "file".
`clamvd`?

2018-04-10 09:06 UTC, scollazo commented on defaults/main.yml
> +# On CentOS the role will use "tcp" if not defined
Itemize this?

```
#  - On CentOS...
#  - On Ubuntu...
```

2018-04-10 09:06 UTC, scollazo commented on tasks/main.yml
> +    - ansible_distribution == "Ubuntu" and ansible_distribution_release != "trusty"
May be we should be explicit here, and use when `ansible_distribution_release= "xenial"`. Did you test this with newer Ubuntu versions (18.04 is almost out!)

2018-04-10 09:06 UTC, scollazo commented on tasks/redhat.yml
> +- name: "Enable and restart services"
This should be triggered only when a configuration change is made

2018-04-10 09:06 UTC, scollazo commented on tasks/ubuntu.yml
> +   # check if clamav is running with file or tcp socket
First letter should be capital

2018-04-10 09:06 UTC, scollazo commented on tasks/ubuntu.yml
> +   # purge clamav-daemon if was installed and socket type will change
First letter should be capital

2018-04-10 09:06 UTC, scollazo commented on tasks/ubuntu.yml
> +# set debconf when installing clamav-daemon
...you know what I'm about to say here...

2018-04-10 09:06 UTC, scollazo commented on tasks/ubuntu.yml
>  - name: "Enable services"
As with Centos, this should be triggered only on configuration change

2018-04-10 09:06 UTC, scollazo commented on templates/etc/clamd.d/scan.conf.j2
> +#TCPAddr 127.0.0.1
Can the tcp bind address and port be converted to vars? There are environments where we need to have clamav listening on a different port, due to 3310 being used by other service.

2018-04-17 21:43 UTC, mamedin commented
@scollazo  thanks for your suggestions. I have changed all that you said except triggering the clamav-daemon restart only on configuration changes. I think I have added a lot of complexity to this role, especially in ubuntu xenial and the clamd is a very light demon that can be restarted without any problem.

2018-04-18 20:18 UTC, sevein approved these changes

2018-04-18 21:38 UTC, hakamine approved these changes
:+1: I added a commit with travis config to run a syntax check on the role, and do a test run with the default configuration, on the currently 3 supported OSes, tests are passing.

2018-04-19 02:32 UTC, sevein commented
> 👍 I added a commit with travis config to run a syntax check on the role, and do a test run with the default configuration, on the currently 3 supported OSes, tests are passing.

🎉 this is interesting, @hakamine. So there's not test assertions other than expecting that the playbook completes successfully, right? I guess that's a good start.

2018-04-20 09:46 UTC, merged